system:
  port: 8043
  debug: false
  log_path: zap.conf
  monitor: :21000

callback:
  return_url: https://test-bkweb.bastionpay.com/v1/basmerchant/callback/trade/complete
  show_url:   https://test-bkweb.bastionpay.com/v1/basmerchant/callback/trade/cancel
  notify_url: https://test-bkweb.bastionpay.com/v1/basmerchant/callback/notify

#redis:
#  network: tcp
#  host: 127.0.0.1
#  port: 6379
#  password: ""
#  database: 0
#  maxIdle: 0
#  maxActive: 10
#  idleTimeout: 5
#  maxOpen: 200
#  prefix: ""

#aws:
#  accesskeyid: AKIAJEJUHBCEJGTFGNHA
#  accesskey:  oflCXIs+8jsbBYffy8lPedKok90NkSSabv8SVY66
#  accesstoken:
#  fileregion: us-east-1
#  filebucket: bastionpay-dev-filetransfer
#  filetimeout: 300


mysql: #多个数据库
  host: testbastion.cka6afgwtw5w.us-east-1.rds.amazonaws.com
  port: 3306
  dbname: bas_merchant
  user: testbastion
  password: testbastion.123
  charset: utf8
  parseTime: false
  maxIdle: 0
  maxOpen: 5
  debug: true

cache:
  vipauth_max_key: 200
  vipauth_timeout: 300
  viplist_max_key:     3
  viplist_timeout: 300
  vipdisable_max_key:  30
  vipdisable_timeout:  300

device:
- id: 860344040771835
  name: game
  addr: ws://iot.bigeapp.com:1883/ws
