system:
  port: 8044
  debug: true
  log_path: zap.conf
  monitor: :21000

redis:
  network: tcp
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 0
  maxIdle: 0
  maxActive: 10
  idleTimeout: 5
  maxOpen: 200
  prefix: ""


mysql: #多个数据库
#  host: testbastion.cka6afgwtw5w.us-east-1.rds.amazonaws.com
  host: 127.0.0.1
  port: 3306
  dbname: bastionpay_activity
#  user: TestDBAdmin
  user: root
#  password: bastionpay.123
  password: chris.fang
  charset: utf8
  parseTime: false
  maxIdle: 0
  maxOpen: 30
  debug: true

award:
  extratime:
    coin: 0.2
    symbol: SHINE
  checkin:
    coin: 1
    symbol: MBABA
  merchantId: 10
  sendTimes: 3
  chanLen: 300
  awardTime: 9:30 #最晚有效考勤奖励时间

api:
  account: 3cf92f367d709aa393f1506482e45528
  secretKey: Coinmerit

gcache:
  secretKey: dingdingsecretkey
  expire: 7200

dingding:
  boJu:
    appKey: dingz6dtso3reztbtvhd
    appSecret: b5mU2LOCCm-ntP4_gHlBBewWu4UfDuKnp-kNhsC_7QR6FBJOPyZSruOvFDtB1k-c
  host: https://oapi.dingtalk.com

company:
  serviceAward:
    coinBase: 5
    symbol: SHINE
    merchantId: 10
    sendTimes: 3
    chanLen: 30
  rubbishClassify:
    coin: [0, 1, 2]
    symbol: SHINE
    merchantId: 10
    sendTimes: 3
    chanLen: 100
  id: [1, 2]
  apiHost: https://test-teammanage.bastionpay.io