language: go

go:
  - 1.8.x
  - 1.9.x

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t d93442cf-8aac-4a40-9aef-125c99119c6e

notifications:
  email:
    on_success: never