system:
  port: 8099
  debug: false
  log_path: zap.conf
  monitor: :21000

callback:
  return_url: https://test-merchant.bastionpay.io/v1/basmerchant/callback/trade/complete
  show_url:   https://test-merchant.bastionpay.io/v1/basmerchant/callback/trade/cancel
  notify_url: https://test-merchantapi.bastionpay.io/v2/bas-merchant/callback/notify


#redis:
#  network: tcp
#  host: 127.0.0.1
#  port: 6379
#  password: ""
#  database: 0
#  maxIdle: 0
#  maxActive: 10
#  idleTimeout: 5
#  maxOpen: 200
#  prefix: ""

#aws:
#  accesskeyid: AKIAJEJUHBCEJGTFGNHA
#  accesskey:  oflCXIs+8jsbBYffy8lPedKok90NkSSabv8SVY66
#  accesstoken:
#  fileregion: us-east-1
#  filebucket: bastionpay-dev-filetransfer
#  filetimeout: 300


#mysql: #多个数据库
#  host: testbastion.cka6afgwtw5w.us-east-1.rds.amazonaws.com
#  port: 3306
#  dbname: bas_merchant
#  user: testbastion
#  password: testbastion.123
#  charset: utf8
#  parseTime: false
#  maxIdle: 0
#  maxOpen: 5
#  debug: true

#paytestdb-cluster.cluster-ckbyno63cpkt.us-east-1.rds.amazonaws.com
mysql: #多个数据库
  host: paytestdb-cluster.cluster-ckbyno63cpkt.us-east-1.rds.amazonaws.com
  port: 3306
  dbname: bastionpay_merchant
  user: TestDBAdmin
  password: bastionpay.123
  charset: utf8
  parseTime: false
  maxIdle: 0
  maxOpen: 5
  debug: true

cache:
  vipauth_max_key: 200
  vipauth_timeout: 300
  viplist_max_key:     3
  viplist_timeout: 300
  vipdisable_max_key:  30
  vipdisable_timeout:  300

device:
- id: 869300033969209
  name: game
  addr: ws://iot.bigeapp.com:1883/ws

payeeid:
  payid: 185
  merchantid: 8

bastionpay_url:
  bastionurl: http://test-openapi.bastionpay.io
  bastionuser: http://test1-user.bastionwallet.com
  quoteurl: http://test-quote.rkuan.com
#https://vendor.beefpay.com/v2/bas-merchant/trade/avali-assets
  #http://test-openapi.bastionpay.io   http://open-api.bastionpay.com

#login:
#  pre_uid: 81
#  password: 123456
#  phone: +086_17671620432
#  zf_pwd: 123456
#  device_id: 394a55969f7bd7061bdaa320db925ac1

login:
  pre_uid: 57
  password: 123456
  phone: +086_17317351119
  zf_pwd: 123456
  device_id: 394a55969f7bd7061bdaa320db925ac1

#atm手续费
fee:
  cash2coin: 0.03
  coin2cash: 0.03