// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assets.proto

/*
Package rpc_account is a generated protocol buffer package.

It is generated from these files:
	assets.proto

It has these top-level messages:
	RequestGetPosns
	Position
	ResponseGetPosns
	RequestDeposit
	ResponseDeposit
	RequestWithdrawal
	ResponseWithdrawal
*/
package rpc_account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestGetPosns struct {
	Tid    uint64   `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	Assets []string `protobuf:"bytes,2,rep,name=assets" json:"assets,omitempty"`
}

func (m *RequestGetPosns) Reset()                    { *m = RequestGetPosns{} }
func (m *RequestGetPosns) String() string            { return proto.CompactTextString(m) }
func (*RequestGetPosns) ProtoMessage()               {}
func (*RequestGetPosns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestGetPosns) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *RequestGetPosns) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

type Position struct {
	Asset     string `protobuf:"bytes,1,opt,name=asset" json:"asset,omitempty"`
	Available string `protobuf:"bytes,2,opt,name=available" json:"available,omitempty"`
	Frozen    string `protobuf:"bytes,3,opt,name=frozen" json:"frozen,omitempty"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Position) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Position) GetAvailable() string {
	if m != nil {
		return m.Available
	}
	return ""
}

func (m *Position) GetFrozen() string {
	if m != nil {
		return m.Frozen
	}
	return ""
}

type ResponseGetPosns struct {
	Tid   uint64      `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	Posns []*Position `protobuf:"bytes,2,rep,name=posns" json:"posns,omitempty"`
}

func (m *ResponseGetPosns) Reset()                    { *m = ResponseGetPosns{} }
func (m *ResponseGetPosns) String() string            { return proto.CompactTextString(m) }
func (*ResponseGetPosns) ProtoMessage()               {}
func (*ResponseGetPosns) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResponseGetPosns) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *ResponseGetPosns) GetPosns() []*Position {
	if m != nil {
		return m.Posns
	}
	return nil
}

type RequestDeposit struct {
	Tid       uint64 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	PaymentId uint64 `protobuf:"varint,2,opt,name=payment_id,json=paymentId" json:"payment_id,omitempty"`
	Asset     string `protobuf:"bytes,3,opt,name=asset" json:"asset,omitempty"`
	Amount    string `protobuf:"bytes,4,opt,name=amount" json:"amount,omitempty"`
	Type      string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
}

func (m *RequestDeposit) Reset()                    { *m = RequestDeposit{} }
func (m *RequestDeposit) String() string            { return proto.CompactTextString(m) }
func (*RequestDeposit) ProtoMessage()               {}
func (*RequestDeposit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestDeposit) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *RequestDeposit) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *RequestDeposit) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *RequestDeposit) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *RequestDeposit) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ResponseDeposit struct {
	Tid       uint64 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	PaymentId uint64 `protobuf:"varint,2,opt,name=payment_id,json=paymentId" json:"payment_id,omitempty"`
	Asset     string `protobuf:"bytes,3,opt,name=asset" json:"asset,omitempty"`
	Available string `protobuf:"bytes,4,opt,name=available" json:"available,omitempty"`
	Frozen    string `protobuf:"bytes,5,opt,name=frozen" json:"frozen,omitempty"`
}

func (m *ResponseDeposit) Reset()                    { *m = ResponseDeposit{} }
func (m *ResponseDeposit) String() string            { return proto.CompactTextString(m) }
func (*ResponseDeposit) ProtoMessage()               {}
func (*ResponseDeposit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResponseDeposit) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *ResponseDeposit) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *ResponseDeposit) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *ResponseDeposit) GetAvailable() string {
	if m != nil {
		return m.Available
	}
	return ""
}

func (m *ResponseDeposit) GetFrozen() string {
	if m != nil {
		return m.Frozen
	}
	return ""
}

type RequestWithdrawal struct {
	Tid       uint64 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	PaymentId uint64 `protobuf:"varint,2,opt,name=payment_id,json=paymentId" json:"payment_id,omitempty"`
	Asset     string `protobuf:"bytes,3,opt,name=asset" json:"asset,omitempty"`
	Amount    string `protobuf:"bytes,4,opt,name=amount" json:"amount,omitempty"`
	Type      string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
}

func (m *RequestWithdrawal) Reset()                    { *m = RequestWithdrawal{} }
func (m *RequestWithdrawal) String() string            { return proto.CompactTextString(m) }
func (*RequestWithdrawal) ProtoMessage()               {}
func (*RequestWithdrawal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RequestWithdrawal) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *RequestWithdrawal) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *RequestWithdrawal) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *RequestWithdrawal) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *RequestWithdrawal) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ResponseWithdrawal struct {
	Tid       uint64 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	PaymentId uint64 `protobuf:"varint,2,opt,name=payment_id,json=paymentId" json:"payment_id,omitempty"`
	Asset     string `protobuf:"bytes,3,opt,name=asset" json:"asset,omitempty"`
	Available string `protobuf:"bytes,4,opt,name=available" json:"available,omitempty"`
	Frozen    string `protobuf:"bytes,5,opt,name=frozen" json:"frozen,omitempty"`
}

func (m *ResponseWithdrawal) Reset()                    { *m = ResponseWithdrawal{} }
func (m *ResponseWithdrawal) String() string            { return proto.CompactTextString(m) }
func (*ResponseWithdrawal) ProtoMessage()               {}
func (*ResponseWithdrawal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResponseWithdrawal) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *ResponseWithdrawal) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *ResponseWithdrawal) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *ResponseWithdrawal) GetAvailable() string {
	if m != nil {
		return m.Available
	}
	return ""
}

func (m *ResponseWithdrawal) GetFrozen() string {
	if m != nil {
		return m.Frozen
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestGetPosns)(nil), "rpc.account.RequestGetPosns")
	proto.RegisterType((*Position)(nil), "rpc.account.Position")
	proto.RegisterType((*ResponseGetPosns)(nil), "rpc.account.ResponseGetPosns")
	proto.RegisterType((*RequestDeposit)(nil), "rpc.account.RequestDeposit")
	proto.RegisterType((*ResponseDeposit)(nil), "rpc.account.ResponseDeposit")
	proto.RegisterType((*RequestWithdrawal)(nil), "rpc.account.RequestWithdrawal")
	proto.RegisterType((*ResponseWithdrawal)(nil), "rpc.account.ResponseWithdrawal")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Accounts service

type AccountsClient interface {
	// List Positions.
	ListPositions(ctx context.Context, in *RequestGetPosns, opts ...grpc.CallOption) (*ResponseGetPosns, error)
	// Deposits.
	Deposits(ctx context.Context, in *RequestDeposit, opts ...grpc.CallOption) (*ResponseDeposit, error)
	// Withdrawals.
	Withdrawals(ctx context.Context, in *RequestWithdrawal, opts ...grpc.CallOption) (*ResponseWithdrawal, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) ListPositions(ctx context.Context, in *RequestGetPosns, opts ...grpc.CallOption) (*ResponseGetPosns, error) {
	out := new(ResponseGetPosns)
	err := grpc.Invoke(ctx, "/rpc.account.Accounts/ListPositions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Deposits(ctx context.Context, in *RequestDeposit, opts ...grpc.CallOption) (*ResponseDeposit, error) {
	out := new(ResponseDeposit)
	err := grpc.Invoke(ctx, "/rpc.account.Accounts/Deposits", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Withdrawals(ctx context.Context, in *RequestWithdrawal, opts ...grpc.CallOption) (*ResponseWithdrawal, error) {
	out := new(ResponseWithdrawal)
	err := grpc.Invoke(ctx, "/rpc.account.Accounts/Withdrawals", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Accounts service

type AccountsServer interface {
	// List Positions.
	ListPositions(context.Context, *RequestGetPosns) (*ResponseGetPosns, error)
	// Deposits.
	Deposits(context.Context, *RequestDeposit) (*ResponseDeposit, error)
	// Withdrawals.
	Withdrawals(context.Context, *RequestWithdrawal) (*ResponseWithdrawal, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_ListPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetPosns)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ListPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.account.Accounts/ListPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ListPositions(ctx, req.(*RequestGetPosns))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Deposits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Deposits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.account.Accounts/Deposits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Deposits(ctx, req.(*RequestDeposit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Withdrawals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWithdrawal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Withdrawals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.account.Accounts/Withdrawals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Withdrawals(ctx, req.(*RequestWithdrawal))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.account.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPositions",
			Handler:    _Accounts_ListPositions_Handler,
		},
		{
			MethodName: "Deposits",
			Handler:    _Accounts_Deposits_Handler,
		},
		{
			MethodName: "Withdrawals",
			Handler:    _Accounts_Withdrawals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assets.proto",
}

func init() { proto.RegisterFile("assets.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xcf, 0x4b, 0xf3, 0x40,
	0x14, 0x6c, 0x9a, 0xa4, 0x34, 0xaf, 0xdf, 0x8f, 0x7e, 0xcb, 0xa7, 0x84, 0xda, 0x6a, 0xd9, 0x53,
	0x41, 0xc8, 0xa1, 0x1e, 0x3d, 0x09, 0x42, 0x11, 0x44, 0x6a, 0x0e, 0x7a, 0x94, 0x6d, 0xb3, 0x62,
	0xa0, 0xcd, 0xc6, 0xbc, 0xad, 0x52, 0xaf, 0x82, 0x47, 0xc1, 0x3f, 0xd6, 0xbb, 0x64, 0x77, 0x4b,
	0x9a, 0x12, 0x3d, 0x48, 0xc1, 0xdb, 0xbe, 0x37, 0x9b, 0xc9, 0xcc, 0x30, 0x09, 0xfc, 0x62, 0x88,
	0x5c, 0x62, 0x90, 0x66, 0x42, 0x0a, 0xd2, 0xca, 0xd2, 0x69, 0xc0, 0xa6, 0x53, 0xb1, 0x48, 0x24,
	0x3d, 0x86, 0xbf, 0x21, 0xbf, 0x5f, 0x70, 0x94, 0x23, 0x2e, 0xc7, 0x02, 0x13, 0x24, 0x6d, 0xb0,
	0x65, 0x1c, 0xf9, 0x56, 0xdf, 0x1a, 0x38, 0x61, 0x7e, 0x24, 0xbb, 0xd0, 0xd0, 0x0c, 0x7e, 0xbd,
	0x6f, 0x0f, 0xbc, 0xd0, 0x4c, 0xf4, 0x0a, 0x9a, 0x63, 0x81, 0xb1, 0x8c, 0x45, 0x42, 0xfe, 0x83,
	0xab, 0xb6, 0xea, 0x39, 0x2f, 0xd4, 0x03, 0xe9, 0x82, 0xc7, 0x1e, 0x58, 0x3c, 0x63, 0x93, 0x19,
	0xf7, 0xeb, 0x0a, 0x29, 0x16, 0x39, 0xef, 0x6d, 0x26, 0x9e, 0x78, 0xe2, 0xdb, 0x0a, 0x32, 0x13,
	0xbd, 0x84, 0x76, 0xc8, 0x31, 0x15, 0x09, 0xf2, 0x2f, 0x54, 0x1d, 0x82, 0x9b, 0xe6, 0x90, 0x12,
	0xd5, 0x1a, 0xee, 0x04, 0x6b, 0xbe, 0x82, 0x95, 0xae, 0x50, 0xdf, 0xa1, 0xcf, 0x16, 0xfc, 0x31,
	0x46, 0x4f, 0x79, 0x9a, 0x83, 0x15, 0x8c, 0x3d, 0x80, 0x94, 0x2d, 0xe7, 0x3c, 0x91, 0x37, 0x71,
	0xa4, 0xe4, 0x3a, 0xa1, 0x67, 0x36, 0x67, 0x51, 0x61, 0xd1, 0x5e, 0xb7, 0x98, 0x87, 0x33, 0xcf,
	0xdf, 0xe9, 0x3b, 0xda, 0x84, 0x9e, 0x08, 0x01, 0x47, 0x2e, 0x53, 0xee, 0xbb, 0x6a, 0xab, 0xce,
	0xf4, 0xd5, 0xca, 0xe3, 0xd6, 0xce, 0xb6, 0x2c, 0xa3, 0x94, 0xb4, 0xf3, 0x79, 0xd2, 0x6e, 0x29,
	0xe9, 0x17, 0x0b, 0xfe, 0x99, 0x58, 0xae, 0x63, 0x79, 0x17, 0x65, 0xec, 0x91, 0xcd, 0x7e, 0x22,
	0x99, 0x37, 0x0b, 0xc8, 0x2a, 0x99, 0xed, 0x2b, 0xf9, 0x56, 0x38, 0xc3, 0x77, 0x0b, 0x9a, 0x27,
	0xba, 0x4f, 0x48, 0x2e, 0xe0, 0xf7, 0x79, 0x8c, 0x72, 0xd5, 0x2b, 0x24, 0xdd, 0x52, 0xdf, 0x36,
	0x3e, 0xa2, 0x4e, 0x6f, 0x03, 0x2d, 0xb7, 0x99, 0xd6, 0xc8, 0x08, 0x9a, 0xa6, 0x01, 0x48, 0xf6,
	0xaa, 0xa8, 0x0c, 0xda, 0xe9, 0x56, 0x32, 0x19, 0x94, 0xd6, 0xc8, 0x18, 0x5a, 0x45, 0x60, 0x48,
	0xf6, 0xab, 0xb8, 0x8a, 0x0b, 0x9d, 0x83, 0x4a, 0xba, 0xe2, 0x02, 0xad, 0x4d, 0x1a, 0xea, 0x3f,
	0x71, 0xf4, 0x11, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x99, 0x62, 0xa2, 0x37, 0x04, 0x00, 0x00,
}
