server:
  #ENV SERVER_PORT
  port: 8010
  #ENV SERVER_DEBUG
  debug: false
db:
  host: 127.0.0.1
  port: 3306
  user: root
  password: tlslpc
  db: account
  max_idle_conn: 10
  max_open_conn: 100
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db:
token:
  secret: WHATISSCRET
  # 单位为 minute
  expiration: 1440
exchange:
  host: 127.0.0.1
  port: 8090
  appkey: 8eec1e97ac602d3228bad33b61efeaae
  signature: 8eec1e97ac602d3228bad33b61efeaae-8eec1e97ac602d3228bad33b61efeaae
ses:
  region: us-east-1
  access_key_id: AKIAIGKZLCWQMJHK3L6A
  secret_key: 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
  sender: ingram.su@blockshine.com
sns:
  region: us-east-1
  access_key_id: AKIAIGKZLCWQMJHK3L6A
  secret_key: 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
ip_find:
  auth: 26c27bb8-84fa-47f8-ac8d-1fccdc720669
path_limits:
#  - path: /login
#    method: post
#    limit: 20
#    # 单位为 second
#    time: 3600
#  - path: /login/ga
#    method: post
#    limit: 20
#    time: 600
wallet:
  host: http://35.173.156.149:8082
  userKey: 1c75c668-f1ab-474b-9dae-9ed7950604b4
  keyPath: ./pem
wallet_paths:
  - /v1/bastionpay/support_assets
  - /v1/bastionpay/asset_attribute
  - /v1/bastionpay/new_address
  - /v1/bastionpay/withdrawal
  - /v1/bastionpay/query_address
  - /v1/bastionpay/get_balance
  - /v1/bastionpay/transaction_bill
  - /v1/bastionpay/transaction_bill_daily
  - /v1/bastionpay/block_height
  - /v1/bastionpay/transaction_message
  - /v1/bastionpay/deposit_order
  - /v1/bastionpay/withdrawal_order
  - /v1/account/readprofile
  - /v1/account/updateprofile
coinmarket:
  url: https://api.coinmarketcap.com
  id_path: ./coinidpair.json

cache:
  audite_max_key: 100000
  audite_timeout: 300

limits:
  id_sms: [20, 86400]  #count，expire
  id_mail: [20, 86400]
  ip_sms: [1, 30, 100, 86400]  #从左到右依次匹配
  ip_mail: [1, 30, 100, 86400] #[count1, expire1, count2, expire2.....]

bas_quote:
  url:
